"""Миграция базы данных

Revision ID: 5e98efd21b0b
Revises: e0d52ff74e3f
Create Date: 2020-04-04 22:00:36.988361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e98efd21b0b'
down_revision = 'e0d52ff74e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('track_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    # ### end Alembic commands ###
