"""Миграция базы данных

Revision ID: e0d52ff74e3f
Revises: fa9638595988
Create Date: 2020-04-04 20:44:31.830357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d52ff74e3f'
down_revision = 'fa9638595988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_name', sa.VARCHAR(), nullable=False),
    sa.Column('track_value', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_name')
    )
    # ### end Alembic commands ###
